server.port=9090

spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Service Discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Customer Service Route
spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://customer-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/customers/**

# Flight Service Route
spring.cloud.gateway.server.webflux.routes[1].id=flight-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://flight-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/flights/**,/api/bookings/**

# ==========================
# Global CORS Configuration
# ==========================
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# CORS Configuration
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOriginPatterns=http://localhost:*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true